# Generated by Django 5.1.3 on 2024-11-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("about", models.TextField()),
                ("used_for", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        default="images/default.png", upload_to="images/"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tree", "Tree"),
                            ("fruit", "fruit"),
                            ("vegetables", "vegetables"),
                            ("flower", "flower"),
                            ("herbs", "herbs"),
                        ],
                        default="tree",
                        max_length=20,
                    ),
                ),
                ("is_edible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
